# configs/export_purchase.yaml
soql: ""
out: "output/Purchase_export.csv"
operation: "query"
page: 100000
pk_chunking: ""
output_mode: "both"   # parent / child / both

object_info:
  - name_ja: "仕入伝票"
    api: "Purchase__c"
  - name_ja: "仕入商品"
    api: "PurchaseDetail__c"

query_options:
  where: ""
  order_by: ""
  limit: ""

child_query_options:
  where: "PurchaseId__c != null"
  order_by: ""
  limit: ""

mappings:
  # 親: Purchase__c（必要な項目だけ残してOK）
  - object: "Purchase__c"
    api: "SlipNumber__c"
  - object: "Purchase__c"
    api: "StoreId__c"
  - object: "Purchase__c"
    api: "SupplierId__c"
  - object: "Purchase__c"
    api: "Status__c"
  - object: "Purchase__c"
    api: "Date__c"
  - object: "Purchase__c"
    api: "MdDataPartitions__c"
  - object: "Purchase__c"
    api: "MdMaintenanceType__c"
  - object: "Purchase__c"
    api: "MdMaintenanceCreateDate__c"
  - object: "Purchase__c"
    api: "MdDocumentType__c"
  - object: "Purchase__c"
    api: "MdSlipNumber__c"
  - object: "Purchase__c"
    api: "CreateDate__c"
  - object: "Purchase__c"
    api: "MdSupplierCode__c"
  - object: "Purchase__c"
    api: "MdOrderExecutionDate__c"
  - object: "Purchase__c"
    api: "StoreCode__c"
  - object: "Purchase__c"
    api: "StaffCode__c"
  - object: "Purchase__c"
    api: "MdUpdatedDate__c"
  - object: "Purchase__c"
    api: "MdLogisticsClassification__c"
  - object: "Purchase__c"
    api: "MdEmployeeCode__c"
  - object: "Purchase__c"
    api: "MdDestinationStoreTCCode__c"
  - object: "Purchase__c"
    api: "MdDestinationStoreCode__c"
  - object: "Purchase__c"
    api: "MdTaxCategory__c"
  - object: "Purchase__c"
    api: "MdAssignedStoreCode__c"
  - object: "Purchase__c"
    api: "MdReturnClassification__c"
  - object: "Purchase__c"
    api: "MdSendDate__c"
  - object: "Purchase__c"
    api: "MdSendDocumentType__c"
  - object: "Purchase__c"
    api: "MdSendSupplierCode__c"
  - object: "Purchase__c"
    api: "MdSendLogisticsClassification__c"
  - object: "Purchase__c"
    api: "MdSendEmployeeCode__c"
  - object: "Purchase__c"
    api: "MdSendDestinationStoreTCCode__c"
  - object: "Purchase__c"
    api: "MdSendDestinationStoreCode__c"
  - object: "Purchase__c"
    api: "MdSendLineNumber__c"
  - object: "Purchase__c"
    api: "MdSendAssignedStoreCode__c"
  - object: "Purchase__c"
    api: "OrderId__c"
  - object: "Purchase__c"
    api: "StaffId__c"
  - object: "Purchase__c"
    api: "LogisticsDivision__c"
  - object: "Purchase__c"
    api: "PurchaseClassfication__c"

  # 子: PurchaseDetail__c
  - object: "PurchaseDetail__c"
    api: "MdDepartmentCode__c"
  - object: "PurchaseDetail__c"
    api: "MdJanCode__c"
  - object: "PurchaseDetail__c"
    api: "MdComment__c"
  - object: "PurchaseDetail__c"
    api: "MdDataPartitions__c"
  - object: "PurchaseDetail__c"
    api: "MdMaintenanceType__c"
  - object: "PurchaseDetail__c"
    api: "MdMaintenanceCreateDate__c"
  - object: "PurchaseDetail__c"
    api: "MdSubCategoryCode__c"
  - object: "PurchaseDetail__c"
    api: "MdDocumentType__c"
  - object: "PurchaseDetail__c"
    api: "MdSlipNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdBasicUnitPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdSupplierCode__c"
  - object: "PurchaseDetail__c"
    api: "MdCancellationClassification__c"
  - object: "PurchaseDetail__c"
    api: "MdMajorCategoryCode__c"
  - object: "PurchaseDetail__c"
    api: "MdOrderExecutionDate__c"
  - object: "PurchaseDetail__c"
    api: "MdInstructionNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdQuantity__c"
  - object: "PurchaseDetail__c"
    api: "MdNewUnitPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdUpdateApplicationId__c"
  - object: "PurchaseDetail__c"
    api: "MdUpdatedDate__c"
  - object: "PurchaseDetail__c"
    api: "MdUpdaterCode__c"
  - object: "PurchaseDetail__c"
    api: "MdUpdateDate__c"
  - object: "PurchaseDetail__c"
    api: "MdCurrentSellingPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdReasonCategory__c"
  - object: "PurchaseDetail__c"
    api: "MdCreatedDate__c"
  - object: "PurchaseDetail__c"
    api: "MdEmployeeCode__c"
  - object: "PurchaseDetail__c"
    api: "MdDestinationStoreTCCode__c"
  - object: "PurchaseDetail__c"
    api: "MdDestinationStoreCode__c"
  - object: "PurchaseDetail__c"
    api: "MdLineNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdAssignedStoreCode__c"

  # (MD送信) 系（存在すれば出力）
  - object: "PurchaseDetail__c"
    api: "MDSendPurchaseDate__c"   # ← 仕入日の正解（MdSendDate__cではない）
  - object: "PurchaseDetail__c"
    api: "MdSendDocumentType__c"
  - object: "PurchaseDetail__c"
    api: "MdSendSlipNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdSendSupplierCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendDepartmentCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendMajorCategoryCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendSubCategoryCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendJanCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendQuantity__c"
  - object: "PurchaseDetail__c"
    api: "MdSendBasicUnitPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdSendCurrentSellingPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdSendNewUnitPrice__c"
  - object: "PurchaseDetail__c"
    api: "MdSendCancellationClassification__c"
  - object: "PurchaseDetail__c"
    api: "MdSendReasonCategory__c"
  - object: "PurchaseDetail__c"
    api: "MdSendInstructionNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdSendComment__c"
  - object: "PurchaseDetail__c"
    api: "MdSendLogisticsClassification__c"
  - object: "PurchaseDetail__c"
    api: "MdSendEmployeeCode__c"
  - object: "PurchaseDetail__c"
    api: "MdSendSendLineNumber__c"
  - object: "PurchaseDetail__c"
    api: "MdSendAssignedStoreCode__c"

  # 結合キーなど
  - object: "PurchaseDetail__c"
    api: "PurchaseId__c"
  - object: "PurchaseDetail__c"
    api: "ProductId__c"
  - object: "PurchaseDetail__c"
    api: "Name"
