master_key: ODM
sf_object: OrderDetailMD__c
operation: upsert
external_id_field: MdOrderDetailNumber__c

input_encoding: cp932
output_encoding: utf-8
lineterminator: "\n"
delimiter: ","
has_header: false
output_csv: output/OrderDetailMD_upsert_ready.csv

owner_id_column: OwnerId
owner_id_value: ""
extra_fields: { }

mapping:
  - { index: 0, field: MdOrderDetailNumber__c }
  - { index: 1, field: MdStoreCode__c }
  - { index: 2, field: ProductJan__c }
  - { index: 3, field: Qty__c }
